#!/usr/bin/env bash
#MISE description="flash keyboard firmware"

echo "When flash firmware, keymap is overwritten by default keymap."
read -p "Do you save latest keymap? (yes/no): " choice
case "$choice" in
  no|No|n|N ) echo "Please save your latest keymap!"; exit 1;;
  * ) echo "Invalid response."; exit 1;;
esac

cd qmk_firmware
qmk flash mtk_mtk64erp_via.uf2
